version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: authdb
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpass
    ports:
      - "3307:3306"  # Expose MySQL to host on port 3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: auth_phpmyadmin
    environment:
      PMA_HOST: mysql
      # PMA_USER: root
      # PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - auth_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  auth_network:
    driver: bridge
